version: 0.0

os: linux
files:
  - source: /target/jenkinstest-0.0.1-SNAPSHOT.war
    destination: /tmp/
hooks:

  ApplicationStop:
    - location: scripts/stop.sh
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 10
